version: '3.9'
services:
  app:
    build: .
    environment:
      DB_HOST: db
      DB_DSN: mysql:host=db;dbname=app
      DB_USER: root
      DB_PASS: example
    volumes:
      - web-data:/var/www/html/web
    depends_on:
      - db
    mem_limit: 200m
    restart: unless-stopped

  db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: app
      MARIADB_AUTO_UPGRADE: '1'
    volumes:
      - db-data:/var/lib/mysql
    command: --max_connections=20 --innodb_buffer_pool_size=32M
    mem_limit: 256m
    restart: unless-stopped

  nginx:
    build: ./docker/nginx
    ports:
      - "8080:80"
    volumes:
      - web-data:/usr/share/nginx/html:ro
    depends_on:
      - app
    environment:
      - ENV_SERVER_NAME=${ENV_SERVER_NAME}
    mem_limit: 50m
    restart: unless-stopped

volumes:
  db-data:
  web-data:
