version: '3.9'
services:
  app:
    build: .
    environment:
      DB_HOST: db
      DB_DSN: mysql:host=db;dbname=app
      DB_USER: root
      DB_PASS: example
    volumes:
      - web-data:/var/www/html/web
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: app
    volumes:
      - db-data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - web-data:/usr/share/nginx/html:ro
    depends_on:
      - app

volumes:
  db-data:
  web-data:
