name: Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Install dependencies
        run: composer install --no-progress --no-interaction
        working-directory: backend
      - name: PHP syntax check
        run: find . -name '*.php' -print0 | xargs -0 -n1 php -l
        working-directory: backend

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: frontend
      - name: Build
        run: yarn build
        working-directory: frontend
      - name: Type check
        run: yarn run check
        working-directory: frontend
