# .github/workflows/deploy.yml
name: Deploy to External Server

on:
  workflow_dispatch:  # Manual trigger via GitHub UI

jobs:
  deploy:
    name: Build & Deploy to External Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            set -e
            set -x # Enable command tracing

            echo "Starting deployment script execution."
            cd "${{ secrets.APP_DIRECTORY }}"
            echo "Pulling latest code from origin..."
            git stash
            git stash clear
            git checkout main
            git pull origin main
            echo "- Git pull completed."

            echo "Taking Docker services down..."
            docker compose down
            echo "- Docker services down."

            echo "Building Docker services (no-cache)..."
            docker compose build --no-cache
            echo "- Docker build completed."

            echo "Bringing Docker services up (detached)..."
            ENV_SERVER_NAME="${{ secrets.PROD_SERVER_NAME }}" docker compose up -d
            echo "- Docker services up."

            echo "Deployment script finished successfully."
            set +x # Disable command tracing
          EOF
