# .github/workflows/deploy.yml
name: Deploy to External Server

on:
  workflow_dispatch:  # Manual trigger via GitHub UI

jobs:
  deploy:
    name: Build & Deploy to External Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            set -e
            set -x # Enable command tracing

            echo "DEBUG: Starting deployment script execution."
            echo "DEBUG: Current directory (before cd):"
            pwd

            echo "DEBUG: Changing to application directory: ${{ secrets.APP_DIRECTORY }}"
            cd "${{ secrets.APP_DIRECTORY }}"
            echo "DEBUG: Current directory (after cd):"
            pwd

            echo "DEBUG: Pulling latest code from origin..."
            git pull origin
            echo "DEBUG: Git pull completed."

            echo "DEBUG: Taking Docker services down..."
            docker compose down
            echo "DEBUG: Docker services down."

            echo "DEBUG: Building Docker services (no-cache)..."
            docker compose build --no-cache
            echo "DEBUG: Docker build completed."

            echo "DEBUG: Bringing Docker services up (detached)..."
            docker compose up -d
            echo "DEBUG: Docker services up."

            echo "DEBUG: Deployment script finished successfully."
            set +x # Disable command tracing
          EOF
