name: PHP Tests

on:
  push:
    branches:
      - main
    paths:
      - '**.php'
      - '.github/workflows/php.yml'
      - 'backend/**'
  pull_request:
    paths:
      - '**.php'
      - '.github/workflows/php.yml'
      - 'backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress
        working-directory: backend
      - name: Run PHPUnit
        run: ./vendor/bin/phpunit --configuration phpunit.xml --coverage-clover coverage.xml
        working-directory: backend
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: phpunit-coverage
          path: backend/coverage.xml
